# Stage 0: build the synthetic test set (no dependencies, nothing confidential involved)
#   python build_sample.py
# reads  sample/sample_source.md   fake diary with planted spans marked {{PP03.a}}text{{/}}
# writes sample/sample.md          the same text without markers -> feed this to Stage 1
#        sample/ground_truth.json  every planted item, read by score.py
#        sample/answer_key.md      the same, for humans
import re, sys, json, pathlib

# prefix: (what it tests, kind, expected verdict, verdicts counted as acceptable, Stage 1 expectation)
CATS = {
    "EX": ("Verbatim copy in another entry", "dup", "SAME", ["SAME"], "found"),
    "FM": ("Same sentence, different formatting (inside a paragraph, bold, wikilink, heading, nested bullet)", "dup", "SAME", ["SAME"], "found"),
    "HW": ("Sentence hard-wrapped over two lines (Stage 1 treats every line as its own note)", "dup", "SAME", ["SAME", "OVERLAP"], "miss"),
    "NR": ("Near-copy: typo, spelling, word order, punctuation", "dup", "SAME", ["SAME", "OVERLAP"], "found"),
    "PP": ("Paraphrase carrying the same information", "dup", "SAME", ["SAME", "OVERLAP"], "found"),
    "OV": ("One version adds a detail", "dup", "OVERLAP", ["OVERLAP", "SAME"], "found"),
    "FR": ("English sentence and its French version", "dup", "SAME", ["SAME", "OVERLAP"], "found"),
    "CW": ("Plain word vs code word (alcohol/sauce, ...)", "dup", "SAME", ["SAME", "OVERLAP"], "found"),
    "GR": ("Same idea written 3 to 7 times", "dup", "SAME", ["SAME", "OVERLAP"], "found"),
    "BL": ("Copy-pasted block of bullets", "dup", "SAME", ["SAME"], "found"),
    "SM": ("One sentence summarising several bullets elsewhere", "dup", "OVERLAP", ["OVERLAP", "SAME"], "partial"),
    "SH": ("Short duplicate, under 40 characters", "dup", "SAME", ["SAME", "OVERLAP"], "found"),
    "ST": ("Parser stress: bullet glued to ---, mid-bullet sentence, e.g./Dr., checkbox, nesting, run-on", "dup", "SAME", ["SAME", "OVERLAP"], "found"),
    "MS": ("Sloppy rewording: lowercase, abbreviations, typos, symbols", "dup", "SAME", ["SAME", "OVERLAP"], "found"),
    "LN": ("Thought sitting in a run of loose lines (no bullets, no blank lines, no full stops)", "dup", "SAME", ["SAME", "OVERLAP"], "found"),
    "NF": ("Same template, different day or event", "neg", "DIFFERENT", ["DIFFERENT"], "any"),
    "CF": ("Same statement with a changed value (conflicting versions, worth a look)", "neg", "DIFFERENT", ["DIFFERENT", "OVERLAP"], "any"),
    "NG": ("Negation or opposite", "neg", "DIFFERENT", ["DIFFERENT"], "any"),
    "TP": ("Same topic, different information", "neg", "DIFFERENT", ["DIFFERENT"], "any"),
}
IDENTICAL = {"EX", "BL"}   # members must be byte-identical copies

here = pathlib.Path(__file__).parent / "sample"
src = (here / "sample_source.md").read_text(encoding="utf-8")
SPAN = re.compile(r"\{\{([A-Z]{2})(\d{2})\.([a-z])\}\}(.*?)\{\{/\}\}", re.S)

items, errors = {}, []
for m in SPAN.finditer(src):
    cat, num, member, text = m.groups()
    if cat not in CATS: errors.append(f"unknown prefix {cat}{num}"); continue
    if "{{" in text: errors.append(f"nested or unclosed marker in {cat}{num}.{member}")
    line = src.count("\n", 0, m.start()) + 1
    items.setdefault(cat + num, {}).setdefault(member, []).append(
        {"line": line, "text": " ".join(text.split())})

clean = SPAN.sub(lambda m: m.group(4), src)
if "{{" in clean or "}}" in clean: errors.append("leftover {{ or }} after stripping markers")
if len(clean.splitlines()) != len(src.splitlines()): errors.append("line count changed")
for iid, members in items.items():
    if len(members) < 2: errors.append(f"{iid} has a single member")
    texts = {s["text"] for spans in members.values() for s in spans}
    if iid[:2] in IDENTICAL and len(texts) != 1: errors.append(f"{iid} members should be identical")
if errors: sys.exit("sample_source.md problems:\n  " + "\n  ".join(errors))

truth = {"categories": {}, "items": []}
for cat, (desc, kind, expected, acceptable, stage1) in CATS.items():
    truth["categories"][cat] = {"description": desc, "kind": kind, "expected": expected,
                                "acceptable": acceptable, "stage1": stage1}
for iid in sorted(items, key=lambda i: (list(CATS).index(i[:2]), i)):
    truth["items"].append({"id": iid, "category": iid[:2], "members": dict(sorted(items[iid].items()))})

(here / "sample.md").write_text(clean, encoding="utf-8")
json.dump(truth, open(here / "ground_truth.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)

with open(here / "answer_key.md", "w", encoding="utf-8") as f:
    f.write("# Answer key for sample.md\n\nGenerated by build_sample.py. Line numbers refer to sample.md.\n\n")
    for cat, c in truth["categories"].items():
        mine = [it for it in truth["items"] if it["category"] == cat]
        f.write(f"## {cat}: {c['description']}\n\n")
        f.write(f"Expected verdict: {c['expected']}")
        if c["stage1"] == "miss": f.write(" (Stage 1 is expected to miss these)")
        if c["stage1"] == "partial": f.write(" (Stage 1 is expected to catch only some)")
        f.write("\n\n")
        for it in mine:
            f.write(f"**{it['id']}**\n\n")
            for member, spans in it["members"].items():
                for s in spans:
                    f.write(f"- {member}, line {s['line']}: {s['text']}\n")
            f.write("\n")

n_pairs = sum(len(it["members"]) * (len(it["members"]) - 1) // 2 for it in truth["items"])
print(f"{len(clean.split())} words, {len(clean)} characters, {len(clean.splitlines())} lines -> sample/sample.md")
print(f"{len(truth['items'])} planted items, {n_pairs} labelled pairs -> sample/ground_truth.json, sample/answer_key.md")
